a = 5
perimetr = 4 * a
area = a * a
print('perimetr = 4 * a', perimetr)
print('area = a * a', area)
d = 10
pi = 3.14
print('length =', length)
b = 10
c = 6
mean = (b+c) / 2
print('mean =', mean)
e = 5
f = 3
sum = e + f
product = e * f
square_a = e ** 2
square_b = f ** 2
print('sum =', sum)
print('product = e * f', product)
print('square_a =', square_a)
print('square_b =', square_b)
